server:
  port: 8081
  servlet:
    context-path: /515code

todo:
  date: "三月二十五号"
  thing: 今天是${todo.date},我们去看电影


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/student?characterEncoding=utf-8
    username: root
    password: 20185584

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  pattern:
    console: "%d - %msg%n"
    file: "%d - %msg%n"
  file:
    name: /Volumes/disk3/天津理工大学/firstCourse/log/four.log
    path: /Volumes/disk3/天津理工大学/firstCourse/log/
  level:
    com.sipc.catalina.LogTest.LogTest: debug
